#!/bin/bash

set -e

# Dev container startup orchestration: bring up the services that the base image
# cannot safely start during build, then keep virtual robot discovery visible.
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
AVAHI_CONF="/etc/avahi/avahi-daemon.conf"
AVAHI_CONFIGURER="$SCRIPT_DIR/configure_avahi.sh"
MDNS_REPUBLISHER="$SCRIPT_DIR/mdns_republisher.py"
MDNS_REPUBLISHER_SUPERVISOR="$SCRIPT_DIR/mdns-republisher-supervisor.sh"
MDNS_REPUBLISHER_LOG="/tmp/mdns-republisher.log"
MDNS_REPUBLISHER_WATCHDOG_LOG="/tmp/mdns-republisher-watchdog.log"
MDNS_REPUBLISHER_SUPERVISOR_LOG="/tmp/mdns-republisher-supervisor.log"
DESKTOP_WATCHDOG_LOG="/tmp/desktop-watchdog.log"
DESKTOP_WATCHDOG_PID_FILE="/tmp/desktop-watchdog.pid"
DESKTOP_WATCHDOG_INTERVAL_SECONDS="${DESKTOP_WATCHDOG_INTERVAL_SECONDS:-5}"
VNC_PORT=5999
NOVNC_PORT=6080
VNC_LOG="/tmp/xtigervnc.log"
NOVNC_LOG="/tmp/novnc.log"
NOVNC_PID_FILE="/tmp/novnc.pid"
HOST_RUNNER_ENV_FILE="$SCRIPT_DIR/../.env"
HOST_RUNNER_SHELL_ENV_FILE="$HOME/.host_runner_env.sh"
HOST_RUNNER_BOOTSTRAP_SCRIPT="$SCRIPT_DIR/host_runner_bootstrap.py"
HOST_RUNNER_DEFAULT_REQUESTS_DIR="/tmp/duckietown/host_runner_requests"
HOST_RUNNER_SHARED_ENV_FILE="$HOST_RUNNER_DEFAULT_REQUESTS_DIR/host_runner_endpoint.env"
HOST_RUNNER_BASHRC_HOOK='[ -f "$HOME/.host_runner_env.sh" ] && . "$HOME/.host_runner_env.sh"'
DOCKER_STATUS="not checked"
DBUS_STATUS="not checked"
AVAHI_STATUS="not checked"
MDNS_STATUS="not checked"
VNC_STATUS="not checked"
NOVNC_STATUS="not checked"

sync_host_forwarding_alias() {
    local source_key="$1"
    local alias_key="$2"
    local alias_value="${!alias_key:-}"
    local source_value="${!source_key:-}"
    local value="$alias_value"

    if [ -z "$value" ]; then
        value="$source_value"
    fi

    if [ -z "$value" ]; then
        return
    fi

    printf 'export %s=%q\n' "$alias_key" "$value" >> "$HOST_RUNNER_SHELL_ENV_FILE"
}

run_host_runner_python() {
    if command -v python3 >/dev/null 2>&1; then
        python3 "$@"
        return
    fi
    if command -v python >/dev/null 2>&1; then
        python "$@"
        return
    fi
    if command -v py >/dev/null 2>&1; then
        py -3 "$@"
        return
    fi

    return 1
}

append_host_runner_env_exports() {
    local env_file="$1"

    if [ ! -f "$env_file" ]; then
        return
    fi

    while IFS='=' read -r key value || [ -n "$key" ]; do
        case "$key" in
            DTS_*HOST_RUNNER_*)
                printf 'export %s=%q\n' "$key" "$value" >> "$HOST_RUNNER_SHELL_ENV_FILE"
                ;;
        esac
    done < "$env_file"
}

scrub_stale_host_runner_endpoint_manifest() {
    local endpoint_url="${DTS_HOST_RUNNER_URL:-}"
    local endpoint_token="${DTS_HOST_RUNNER_TOKEN:-}"

    if [ -z "$endpoint_url" ] && [ -z "$endpoint_token" ]; then
        return
    fi
    if [ ! -f "$HOST_RUNNER_SHARED_ENV_FILE" ]; then
        return
    fi

    if ! run_host_runner_python \
        "$HOST_RUNNER_BOOTSTRAP_SCRIPT" \
        scrub-endpoint \
        --endpoint-file "$HOST_RUNNER_SHARED_ENV_FILE" \
        --expected-url "$endpoint_url" \
        --expected-token "$endpoint_token" \
        --quiet
    then
        echo "Warning: failed to reconcile the host-runner endpoint manifest." >&2
    fi
}

sync_host_runner_shell_environment() {
    : > "$HOST_RUNNER_SHELL_ENV_FILE"
    echo "# Generated by workspace startup-script.sh" > "$HOST_RUNNER_SHELL_ENV_FILE"

    if [ -f "$HOST_RUNNER_ENV_FILE" ]; then
        append_host_runner_env_exports "$HOST_RUNNER_ENV_FILE"
    else
        for key in DTS_HOST_RUNNER_URL DTS_HOST_RUNNER_TOKEN DTS_HOST_RUNNER_ENGINE_HOST DTS_HOST_RUNNER_TIMEOUT DTS_HOST_RUNNER_REQUESTS_DIR; do
            value="${!key:-}"
            if [ -n "$value" ]; then
                printf 'export %s=%q\n' "$key" "$value" >> "$HOST_RUNNER_SHELL_ENV_FILE"
            fi
        done
    fi

    if [ -f "$HOST_RUNNER_SHARED_ENV_FILE" ]; then
        append_host_runner_env_exports "$HOST_RUNNER_SHARED_ENV_FILE"
    fi

    if ! grep -Fq 'export DTS_HOST_RUNNER_REQUESTS_DIR=' "$HOST_RUNNER_SHELL_ENV_FILE"; then
        printf 'export %s=%q\n' "DTS_HOST_RUNNER_REQUESTS_DIR" "$HOST_RUNNER_DEFAULT_REQUESTS_DIR" >> "$HOST_RUNNER_SHELL_ENV_FILE"
    fi

    sync_host_forwarding_alias "DOCKER_REGISTRY" "HOST_DOCKER_REGISTRY"
    sync_host_forwarding_alias "DTSHELL_COMMANDS" "HOST_DTSHELL_COMMANDS"
    sync_host_forwarding_alias "DTS_HOST_RUNNER_FRONTEND_URL" "HOST_DTS_HOST_RUNNER_FRONTEND_URL"

    if ! grep -Fq "$HOST_RUNNER_BASHRC_HOOK" "$HOME/.bashrc"; then
        printf '\n%s\n' "$HOST_RUNNER_BASHRC_HOOK" >> "$HOME/.bashrc"
    fi

    # shellcheck disable=SC1090
    . "$HOST_RUNNER_SHELL_ENV_FILE"
    scrub_stale_host_runner_endpoint_manifest
}

interface_exists() {
    local iface="$1"
    # ip returns non-zero for missing interfaces without needing text parsing.
    ip -o link show "$iface" >/dev/null 2>&1
}

detect_publish_interface() {
    local iface
    # Prefer the default route because that is the interface visible outside the
    # nested Docker network.
    iface="$(ip -4 route show default 2>/dev/null | awk 'NR==1 {print $5}')"
    if [ -z "$iface" ]; then
        iface="$(ip -o link show 2>/dev/null | awk -F': ' '{print $2}' | grep -E '^(eth|en|wlan)' | head -n 1)"
    fi
    if [ -z "$iface" ]; then
        iface="eth0"
    fi
    echo "$iface"
}

detect_source_interface() {
    # docker0 is the normal bridge for virtual Duckietown robot containers.
    if interface_exists "docker0"; then
        echo "docker0"
        return
    fi

    local iface
    iface="$(ip -o link show 2>/dev/null | awk -F': ' '{print $2}' | grep '^br-' | head -n 1)"
    if [ -n "$iface" ]; then
        echo "$iface"
        return
    fi

    echo "docker0"
}

wait_for_docker_ready() {
    local max_attempts=30
    local attempt=1
    # docker-in-docker can still be initializing after its startup script exits.
    while [ "$attempt" -le "$max_attempts" ]; do
        if docker info >/dev/null 2>&1; then
            return 0
        fi
        sleep 2
        attempt=$((attempt + 1))
    done
    return 1
}

port_listening() {
    local port="$1"
    ss -H -ltn 2>/dev/null | awk -v suffix=":${port}" '
        $4 ~ suffix "$" { found = 1 }
        END { exit !found }
    '
}

wait_for_port() {
    local port="$1"
    local max_attempts="${2:-30}"
    local attempt=1

    while [ "$attempt" -le "$max_attempts" ]; do
        if port_listening "$port"; then
            return 0
        fi
        sleep 1
        attempt=$((attempt + 1))
    done

    return 1
}

clean_stale_desktop_state() {
    if ! port_listening "$VNC_PORT"; then
        sudo rm -f /tmp/.X11-unix/X99 /tmp/.X99-lock 2>/dev/null || true
    fi

    if ! port_listening "$NOVNC_PORT"; then
        rm -f "$NOVNC_PID_FILE"
    fi
}

start_vnc_desktop() {
    echo "Starting VNC desktop..."
    setsid tigervncserver :99 -SecurityTypes None -localhost >"$VNC_LOG" 2>&1 </dev/null &
}

start_novnc_desktop() {
    if [ ! -d "/usr/local/novnc/websockify-0.10.0" ]; then
        NOVNC_STATUS="noVNC installation not found"
        return 1
    fi

    echo "Starting noVNC desktop..."
    (
        cd /usr/local/novnc/websockify-0.10.0
        exec setsid python3 -m websockify --web /usr/local/novnc/noVNC-1.3.0 "$NOVNC_PORT" "localhost:${VNC_PORT}"
    ) >"$NOVNC_LOG" 2>&1 </dev/null &
    echo $! >"$NOVNC_PID_FILE"
}

ensure_desktop_services() {
    if [ ! -f "/usr/local/share/desktop-init.sh" ]; then
        VNC_STATUS="desktop-lite startup script not found"
        NOVNC_STATUS="desktop-lite startup script not found"
        return 0
    fi

    clean_stale_desktop_state

    if ! port_listening "$VNC_PORT"; then
        start_vnc_desktop
        if wait_for_port "$VNC_PORT"; then
            echo "VNC started on port ${VNC_PORT}"
            VNC_STATUS="running on port ${VNC_PORT}"
        else
            echo "ERROR: VNC failed to start. Check ${VNC_LOG}"
            VNC_STATUS="not detected; see ${VNC_LOG}"
        fi
    else
        VNC_STATUS="already running on port ${VNC_PORT}"
    fi

    if port_listening "$VNC_PORT"; then
        if ! port_listening "$NOVNC_PORT"; then
            if start_novnc_desktop && wait_for_port "$NOVNC_PORT"; then
                echo "noVNC started on port ${NOVNC_PORT}"
                NOVNC_STATUS="running at http://localhost:${NOVNC_PORT}"
            elif [ "$NOVNC_STATUS" != "noVNC installation not found" ]; then
                echo "WARNING: noVNC may not have started. Check ${NOVNC_LOG}"
                NOVNC_STATUS="not detected; see ${NOVNC_LOG}"
            fi
        else
            NOVNC_STATUS="already running at http://localhost:${NOVNC_PORT}"
        fi
    else
        NOVNC_STATUS="not started because VNC is unavailable"
    fi

    return 0
}

desktop_watchdog_is_running() {
    local watchdog_pid watchdog_command

    if [ ! -f "$DESKTOP_WATCHDOG_PID_FILE" ]; then
        return 1
    fi

    watchdog_pid="$(tr -d '[:space:]' <"$DESKTOP_WATCHDOG_PID_FILE")"
    if [ -z "$watchdog_pid" ] || ! kill -0 "$watchdog_pid" 2>/dev/null; then
        rm -f "$DESKTOP_WATCHDOG_PID_FILE"
        return 1
    fi

    watchdog_command="$(ps -ww -p "$watchdog_pid" -o command= 2>/dev/null || true)"
    if printf '%s\n' "$watchdog_command" | grep -F -- "$SCRIPT_DIR/startup-script.sh --desktop-watchdog" >/dev/null 2>&1; then
        return 0
    fi

    rm -f "$DESKTOP_WATCHDOG_PID_FILE"
    return 1
}

start_desktop_watchdog() {
    if desktop_watchdog_is_running; then
        return 0
    fi

    nohup bash "$SCRIPT_DIR/startup-script.sh" --desktop-watchdog >"$DESKTOP_WATCHDOG_LOG" 2>&1 </dev/null &
    echo $! >"$DESKTOP_WATCHDOG_PID_FILE"
}

run_desktop_watchdog() {
    trap 'rm -f "$DESKTOP_WATCHDOG_PID_FILE"' EXIT

    while true; do
        ensure_desktop_services
        sleep "$DESKTOP_WATCHDOG_INTERVAL_SECONDS"
    done
}

describe_caroot() {
    if [ -z "${CAROOT:-}" ]; then
        echo "not configured"
        return
    fi

    if [ ! -d "$CAROOT" ]; then
        echo "missing at $CAROOT"
        return
    fi

    if [ -f "$CAROOT/rootCA.pem" ] && [ -f "$CAROOT/rootCA-key.pem" ]; then
        echo "ready at $CAROOT"
        return
    fi

    echo "mounted at $CAROOT, but mkcert CA files were not found"
}

print_workspace_health_summary() {
    local caroot_status
    caroot_status="$(describe_caroot)"

    cat <<EOF

Duckietown workspace startup summary
  Docker: ${DOCKER_STATUS}
  D-Bus: ${DBUS_STATUS}
  Avahi: ${AVAHI_STATUS}
  Virtual robot discovery: ${MDNS_STATUS}
  VNC desktop: ${VNC_STATUS}
  noVNC browser desktop: ${NOVNC_STATUS}
  mkcert CA: ${caroot_status}

Useful endpoints and logs
  noVNC: http://localhost:6080
  mDNS republisher: ${MDNS_REPUBLISHER_LOG}
  mDNS watchdog: ${MDNS_REPUBLISHER_WATCHDOG_LOG}
  noVNC log: /tmp/novnc.log
  VNC log: /tmp/xtigervnc.log
EOF
}

stop_existing_mdns_supervisors() {
    # VS Code may rerun the startup script in an existing container; restart the
    # watchdog so it picks up the latest script and interface values.
    if pgrep -f 'mdns-republisher-supervisor.sh' >/dev/null 2>&1; then
        echo "Restarting Duckietown mDNS republisher supervisor..."
        pkill -f 'mdns-republisher-supervisor.sh' >/dev/null 2>&1 || true
        sleep 1
    fi
}

repair_git_lfs_config() {
    # Dev container tooling can copy host Git LFS filter paths into the container.
    # Reinstall filters only when the configured absolute executable is invalid.
    if ! command -v git >/dev/null 2>&1 || ! command -v git-lfs >/dev/null 2>&1; then
        return
    fi

    local bad_lfs_executable
    bad_lfs_executable="$(git config --global --get-regexp '^filter\.lfs\.' 2>/dev/null | awk '
        {
            split($2, parts, " ")
            executable = parts[1]
            if (executable ~ /^\//) {
                print executable
                exit
            }
        }
    ')"

    if [ -n "$bad_lfs_executable" ] && [ ! -x "$bad_lfs_executable" ]; then
        echo "Repairing Git LFS filter config for this container..."
        git lfs install --force >/dev/null
    fi
}

if [ "${1:-}" = "--desktop-watchdog" ]; then
    run_desktop_watchdog
    exit 0
fi

# Configure DNS resolver options
# The short timeout and single-request-reopen setting reduce resolver stalls in
# nested Docker networking during dev container startup.
sudo grep -q "single-request-reopen" /etc/resolv.conf || echo "options timeout:1 attempts:1 single-request-reopen" | sudo tee -a /etc/resolv.conf > /dev/null

# Start D-Bus daemon (required for Avahi)
if ! pgrep -x dbus-daemon > /dev/null; then
    echo "Starting D-Bus daemon..."
    sudo mkdir -p /var/run/dbus
    # Remove stale PID file if it exists
    sudo rm -f /run/dbus/pid
    sudo dbus-daemon --system --fork
fi
if pgrep -x dbus-daemon > /dev/null; then
    DBUS_STATUS="running"
else
    DBUS_STATUS="not detected"
fi

# Fix Docker credential store issue
# Keep Docker CLI auth config minimal inside the container so host credential
# helpers are not referenced from an environment where they do not exist.
mkdir -p ~/.docker
echo "{}" > ~/.docker/config.json

# Repair host-specific Git LFS paths copied into the container by the dev container tooling.
repair_git_lfs_config

# Make the latest host-runner contract available to interactive shells even if
# the container environment was created with stale Compose interpolation.
sync_host_runner_shell_environment

# Call docker-in-docker startup script
if [ -f "/usr/local/share/docker-init.sh" ]; then
    if docker info >/dev/null 2>&1; then
        echo "Docker already healthy; skipping docker-in-docker re-initialization"
    else
        echo "Starting Docker via docker-in-docker feature..."
        /usr/local/share/docker-init.sh 2>&1 | grep -v -E "(echo: write error|Device or resource busy|Failed to enable nesting, retrying)" || true
    fi
fi
if docker info >/dev/null 2>&1; then
    DOCKER_STATUS="ready"
else
    DOCKER_STATUS="not ready yet"
fi

# Configure and start Avahi daemon
SOURCE_INTERFACE="$(detect_source_interface)"
PUBLISH_INTERFACE="$(detect_publish_interface)"
echo "Configuring Avahi for ${SOURCE_INTERFACE} to ${PUBLISH_INTERFACE} republishing..."
# Bind Avahi to the host-visible interface; the Python republisher handles the
# selected Docker bridge separately.
sudo bash "$AVAHI_CONFIGURER" "$AVAHI_CONF" "$PUBLISH_INTERFACE"
sudo avahi-daemon -k >/dev/null 2>&1 || true
sudo pkill -x avahi-daemon >/dev/null 2>&1 || true
sudo rm -f /run/avahi-daemon/pid
echo "Starting Avahi daemon..."
sudo avahi-daemon -D
if pgrep -x avahi-daemon > /dev/null; then
    AVAHI_STATUS="running on ${PUBLISH_INTERFACE}"
else
    AVAHI_STATUS="not detected"
fi

# Republish virtual robot mDNS records on the dev container interface that
# the host can see. The records point to the dev container IP; Docker-published
# robot ports provide the actual path to services such as DTPS.
if [ ! -f "$MDNS_REPUBLISHER" ]; then
    echo "WARNING: mDNS republisher not found at $MDNS_REPUBLISHER"
    MDNS_STATUS="republisher script missing"
elif [ ! -f "$MDNS_REPUBLISHER_SUPERVISOR" ]; then
    echo "WARNING: mDNS republisher supervisor not found at $MDNS_REPUBLISHER_SUPERVISOR"
    MDNS_STATUS="supervisor script missing"
else
    # Docker can be slow to come up after system/container restarts.
    # Do not fail startup if it is not immediately ready.
    if wait_for_docker_ready; then
        DOCKER_STATUS="ready"
    else
        echo "WARNING: Docker not ready during startup; republisher watchdog will retry automatically"
        DOCKER_STATUS="not ready yet; mDNS watchdog will retry"
    fi

    chmod +x "$MDNS_REPUBLISHER_SUPERVISOR" >/dev/null 2>&1 || true

    stop_existing_mdns_supervisors

    echo "Starting Duckietown mDNS republisher..."
    nohup "$MDNS_REPUBLISHER_SUPERVISOR" \
        "$MDNS_REPUBLISHER_LOG" \
        "$MDNS_REPUBLISHER_WATCHDOG_LOG" \
        "$SOURCE_INTERFACE" \
        "$PUBLISH_INTERFACE" \
        >>"$MDNS_REPUBLISHER_SUPERVISOR_LOG" 2>&1 </dev/null &
    disown

    # Best-effort startup check so failures are visible quickly.
    for _ in $(seq 1 10); do
        if pgrep -f "/usr/bin/python3 $MDNS_REPUBLISHER" >/dev/null 2>&1; then
            break
        fi
        sleep 1
    done
    if ! pgrep -f "/usr/bin/python3 $MDNS_REPUBLISHER" >/dev/null 2>&1; then
        echo "WARNING: mDNS republisher process not detected after startup"
        MDNS_STATUS="not detected; see ${MDNS_REPUBLISHER_WATCHDOG_LOG}"
    else
        MDNS_STATUS="running"
    fi
fi

# Reconcile desktop services at startup, then keep them healthy in the background.
mkdir -p "$HOME/.vnc" "$HOME/.mozilla/firefox"
ensure_desktop_services
start_desktop_watchdog

print_workspace_health_summary
